spring.datasource.url=jdbc:h2:mem:course;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
#if (SQL_LOGGER.isDebugEnabled()) {
#SQL_LOGGER.debug(statement);              // przez SLF4J → Logback
#}
#if (logToStdout) {
#System.out.println("Hibernate: " + statement);  // prosto na stdout
#}
#show-sql dubluje to co pokazuje juz logging.level.org.hibernate.SQL=DEBUG logger SLF4J przez logback
#show-sql pisze bez timestampu bez poziomu i bez nazwy wątku
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
